# Generated by Django 5.2.9 on 2025-12-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_reset_token_expiry_alter_user_reset_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_token',
            new_name='email_verify_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reset_token_expiry',
            new_name='email_verify_token_expiry',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
