# Generated by Django 5.2.9 on 2025-12-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_reset_token_user_email_verify_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verify_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verify_token_expiry',
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
